variable "component"{}
variable "env"{}
variable "instance_type"{}
variable "subnet_id"{}
variable "app_port"{}
variable "server_app_port"{}
variable "vpc_id"{}
variable "bastion_node"{}
variable "lb_subnets"{}
